users:
  id: string
  name: string
  labelName: string
  address: string

follows:
  fromAddress: string
  toAddress: string

transactions:
  userAddress: string
  blockSignedAt: string
  txHash: string
  fromAddress: string
  toAddress: string
  value: number
  logEvents:
    senderName: string
    senderAddress: string
    decoded:
      name: string
      signature: string
      params:
        name: string
        type: string
        value: string