name: club
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  package_info: ^2.0.2
  app_review: ^2.1.2+1
  freezed_annotation: ^2.1.0
  riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.2

  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_analytics: ^10.0.3
  firebase_crashlytics: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner:
  json_serializable:
  freezed: ^2.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/
